name: Ready To Review 
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  front-end:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: make release-build

      - name: Linter 
        run: make release-lint

      - name: Unit tests
        run: make release-test
