name: Build Release 
# add tag to commit
on:
  push:
    branches:
      - release

jobs:
  build-release: 
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: make build

      - name: Linter 
        run: make lint

      - name: Unit tests
        run: make test

      - name: e2e tests
        run: make test-e2e

      # - name: Get version
      #   id: package-version
      #   run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      # - name: Create Git tag
      #   run: |
      #     git tag v${{ steps.package-version.outputs.version }}
      #     git push origin v${{ steps.package-version.outputs.version }}

      # - name: Publish release
      #   run: make release-publish
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
