name: Test
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review


jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: make build

      - name: Linter 
        run: make lint

      - name: Unit tests
        run: make test

      - name: e2e tests
        run: make test-e2e


